services:
  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER:-EnterpriseClaimsLocal}
      Jwt__Audience: ${JWT_AUDIENCE:-EnterpriseClaimsApi}
      ReverseProxy__Clusters__customer-api__Destinations__destination1__Address: http://customer-api:8080/
      ReverseProxy__Clusters__claims-api__Destinations__destination1__Address: http://claims-api:8080/
    ports:
      - "8080:8080"
    depends_on:
      - customer-api
      - claims-api
      - notification-worker

  customer-api:
    build:
      context: .
      dockerfile: src/Services/Customer.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER:-EnterpriseClaimsLocal}
      Jwt__Audience: ${JWT_AUDIENCE:-EnterpriseClaimsApi}
    ports:
      - "8081:8080"

  claims-api:
    build:
      context: .
      dockerfile: src/Services/Claims.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER:-EnterpriseClaimsLocal}
      Jwt__Audience: ${JWT_AUDIENCE:-EnterpriseClaimsApi}
      ConnectionStrings__ClaimsDb: "Server=sqlserver,1433;Database=ClaimsDb;User Id=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True"
    ports:
      - "8082:8080"
    depends_on:
      - sqlserver

  notification-worker:
    build:
      context: .
      dockerfile: src/Workers/Notification.Worker/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Development
      LocalNotifications__SeedFakeClaimSubmittedEvent: "true"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"
    ports:
      - "1433:1433"
